{{ if .Values.prometheus.enable }}
{{ if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: "{{ $.Release.Namespace }}"
  labels:
  {{- include "chart.labels" . | nindent 4 }}
{{- with .Values.serviceMonitor.additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: "{{ .Values.interval }}s"
{{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml .Values.serviceMonitor.metricRelabelings | indent 8 }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 8 }}
{{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- range .Values.serviceMonitor.podTargetLabels }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{ end }}
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "chart.labels" . | nindent 6 }}
spec:
  type: ClusterIP
  selector:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: metrics
{{ end }}
