apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-ephemeral-storage-metrics
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: "{{ .Values.interval }}s"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-ephemeral-storage-metrics
  labels:
    {{- include "chart.labels" . | nindent 6 }}
spec:
  type: ClusterIP
  selector:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: metrics
