
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ephemeral-storage-metrics
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: {{ .Release.Name }}
  {{- include "chart.labels" . | nindent 4 }}
  name: k8s-ephemeral-storage-metrics
  namespace: {{ .Release.Namespace }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ephemeral-storage-metrics
  labels:
  {{- include "chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: k8s-ephemeral-storage-metrics
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8s-ephemeral-storage-metrics
  apiGroup: rbac.authorization.k8s.io

