{{ if .Values.dev.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrink-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shrink-test
  template:
    metadata:
      name: shrink-test
      labels:
        name: shrink-test
    spec:
      containers:
        - image: "{{ .Values.dev.shrink.image }}"
          imagePullPolicy: "{{ .Values.dev.shrink.imagePullPolicy }}"
          name: shrink-test
          resources:
            requests:
              ephemeral-storage: "1Mi"
            limits:
              ephemeral-storage: "60Mi"
          volumeMounts:
            - mountPath: /cache
              name: cache-volume-1
            - mountPath: /cachez
              name: cache-volume-3
      volumes:
        - name: cache-volume-1
          emptyDir:
            sizeLimit: 24Mi
        - name: cache-volume-3
          emptyDir:
            sizeLimit: 24Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grow-test
  template:
    metadata:
      name: grow-test
      labels:
        name: grow-test
    spec:
      containers:
        - image: "{{ .Values.dev.grow.image }}"
          imagePullPolicy: "{{ .Values.dev.grow.imagePullPolicy }}"
          name: grow-test
          resources:
            requests:
              ephemeral-storage: "1Mi"
            limits:
              ephemeral-storage: "60Mi"
          volumeMounts:
            - mountPath: /cache
              name: cache-volume-two
            - mountPath: /cachez
              name: cache-volume-four
      volumes:
        - name: cache-volume-two
          emptyDir:
            sizeLimit: 24Mi
        - name: cache-volume-four
          emptyDir:
            sizeLimit: 24Mi
 {{ end }}
