{{ if .Values.dev.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrink-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shrink-test
  template:
    metadata:
      name: shrink-test
      labels:
        name: shrink-test
    spec:
      containers:
        - image: ghcr.io/jmcgrath207/k8s-ephemeral-storage-shrink-test:latest
          imagePullPolicy: "{{ .Values.dev.image.imagePullPolicy }}"
          name: shrink-test
          resources:
            requests:
              ephemeral-storage: "1Mi"
            limits:
              ephemeral-storage: "5Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grow-test
  template:
    metadata:
      name: grow-test
      labels:
        name: grow-test
    spec:
      containers:
        - image: ghcr.io/jmcgrath207/k8s-ephemeral-storage-grow-test:latest
          imagePullPolicy: "{{ .Values.dev.image.imagePullPolicy }}"
          name: grow-test
          resources:
            requests:
              ephemeral-storage: "1Mi"
            limits:
              ephemeral-storage: "5Mi"
 {{ end }}
