{
 "title": "Kubernetes / Ephemeral Storage Nodes",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(ephemeral_storage_node_capacity,node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Usage in Bytes by Namespace",
   "type": "timeseries",
   "description": "Storage usage in bytes by namespaces on the Kubernetes cluster",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (ephemeral_storage_pod_usage{node_name=~\"${node}\"})",
     "legendFormat": "{{pod_namespace}}"
    }
   ]
  },
  {
   "title": "Node Storage Usage Bytes",
   "type": "timeseries",
   "description": "Total capacity of the ephemeral storage for nodes with their usage bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ephemeral_storage_node_capacity{node_name=~\"${node}\"}",
     "legendFormat": "Total of {{node_name}}"
    },
    {
     "expr": "ephemeral_storage_node_capacity{node_name=~\"${node}\"} - ephemeral_storage_node_available{node_name=~\"${node}\"}",
     "legendFormat": "Used by {{node_name}}"
    }
   ]
  },
  {
   "title": "Node Storage Usage Percentage",
   "type": "timeseries",
   "description": "Percentage of ephemeral storage used on nodes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ephemeral_storage_node_percentage{node_name=~\"${node}\"}\r\n",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}